apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-queue-master
  namespace: tekton-pipelines
spec:
  params:
    - name: namespace

  workspaces:
  - name: source

  steps:
    - name: deploy
      workingDir: $(workspaces.source.path)/microservice/deploy
      image: bryandollery/terraform-packer-aws-alpine
      script: |
        #!/usr/bin/env bash
          echo "inside script"
          ls -aAlth
          kubectl apply -f queue-master-dep.yml -f queue-master-svc.yml -n $(params.namespace)
