apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-shipping
  namespace: tekton-pipelines
spec:
  params:
    - name: namespace

  workspaces:
  - name: source

  steps:
    - name: deploy
      workingDir: $(workspaces.source.path)/microservice/deploy
      image: bryandollery/terraform-packer-aws-alpine
      script: |
        #!/usr/bin/env bash
          echo "inside script"
          kubectl apply -f rabbitmq-dep.yml -f rabbitmq-svc.yml -n $(params.namespace) 
          kubectl apply -f shipping-dep.yml -f shipping-svc.yml -n $(params.namespace)

