apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: payment-pipeline
  namespace: tekton-pipelines
spec:
  resources:
    - name: repo
      type: git
  tasks:

    # build docker image
    - name: build-payment
      taskRef:
        name: build-payment
      resources:
        inputs:
          - name: repo
            resource: repo

    # deploy to test namespace
    - name: deploy-payment
      taskRef:
        name: deploy-payment
      runAfter:
        - build-payment
      resources:
        inputs:
          - name: repo
            resource: repo
