apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-frontend
  namespace: tekton-pipelines
spec:
  params:
    - name: folderPath
      type: string
      default: /workspace/repo/microservice/front-end
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: deploy
      image: bryandollery/terraform-packer-aws-alpine
      script: |
        #!/usr/bin/env bash
<<<<<<< HEAD
          echo "inside script"
          cd $(params.folderPath)
=======
          echo "inside and trying params.path2context"
          cd $(params.frontendPath)/deploy
>>>>>>> 479b607dc4e482fa500f0a93955dbaa74dfa4913
          ls -aAlth
          kubectl version --short=true
          kubectl apply -f deploy.yml -f service.yml -f ingress.yml -n test

