apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
<<<<<<< HEAD
  name: frontend-pr
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: frontend-pipeline
  resources:
  - name: repo
    resourceRef:
      name: level3-project
