apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-pipeline
<<<<<<< HEAD
  namespace: tekton-pipelines
=======
>>>>>>> 479b607dc4e482fa500f0a93955dbaa74dfa4913
spec:
  resources:
    - name: repo
      type: git
  tasks:

    # build docker image
    - name: build-frontend
      taskRef:
        name: build-frontend
      resources:
        inputs:
          - name: repo
            resource: repo
<<<<<<< HEAD

    # to-do unit-testing 

=======
>>>>>>> 479b607dc4e482fa500f0a93955dbaa74dfa4913
    # deploy to test namespace
    - name: deploy-frontend
      taskRef:
        name: deploy-frontend
      runAfter:
        - build-frontend
      resources:
        inputs:
          - name: repo
            resource: repo

    # to-do integration testing
    
    # to-do deploy to prod namespace
