apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
<<<<<<< HEAD
  name: frontend-pr
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
=======
  name: pr-frontend
spec:
  serviceAccountName: abdul
>>>>>>> 479b607dc4e482fa500f0a93955dbaa74dfa4913
  pipelineRef:
    name: frontend-pipeline
  resources:
  - name: repo
    resourceRef:
      name: level3-project
