apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-pipeline
spec:
  resources:
    - name: repo
      type: git
  tasks:
    # build docker image
    - name: build-frontend
      taskRef:
        name: test
      resources:
        inputs:
          - name: repo
            resource: repo
    # deploy to test namespace
    - name: deploy-frontend
      taskRef:
        name: deploy-frontend
      runAfter:
        - test
      resources:
        inputs:
          - name: repo
            resource: repo










