apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-user-pipeline
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: user-pipeline
  params:
  - name: db-image
    value: abdul125/user-db:test
  - name: image
    value: abdul125/user:test
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: user-pvc