apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: payment-pipeline
  namespace: tekton-pipelines
spec:
  workspaces:
  - name: shared-workspace

  params:
  - name: image

  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: https://github.com/abdul125/level3-project
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"

  - name: build-payment
    taskRef:
      name: build-payment
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: IMAGE
      value: $(params.image)
    - name: EXTRA_ARGS
      value: "--skip-tls-verify"

  - name: verify-digest
    runAfter:
    - build-payment
    params:
    - name: digest
      value: $(tasks.build-payment.results.IMAGE-DIGEST)
    taskSpec:
      params:
      - name: digest
      steps:
      - name: bash
        image: ubuntu
        script: |
          echo $(params.digest)
          case .$(params.digest) in
            ".sha"*) exit 0 ;;
            *)       echo "Digest value is not correct" && exit 1 ;;
          esac

  - name: deploy-to-test
    taskRef:
      name: deploy-payment
    runAfter:
    - verify-digest
    workspaces:
    - name: source
      workspace: shared-workspace
    params: 
    - name: namespace
      value: "test"

  - name: e2e-test
    taskRef:
      name: e2e-test
    runAfter:
    - deploy-to-test
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: deploy-to-production
    taskRef:
      name: deploy-payment
    runAfter:
    - e2e-test
    workspaces:
    - name: source
      workspace: shared-workspace
    params: 
    - name: namespace
      value: "prod"

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-payment-pipeline
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: payment-pipeline
  params:
  - name: image
    value: abdul125/payment
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: payment-pvc
