apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-orders-pipeline
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: orders-pipeline
  params:
  - name: image
    value: abdul125/orders:test
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: orders-pvc