apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-catalogue-pipeline
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: catalogue-pipeline
  params:
  - name: db-image
    value: abdul125/catalogue-db:test
  - name: image
    value: abdul125/catalogue:test
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: catalogue-pvc