apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  labels:
    app: orders
    type: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: abdul125/orders
        ports:
        - containerPort: 
