apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: level3-project
  namespace: tekton-pipelines
spec:
  type: git
  params:
    - name: url
      value: https://github.com/abdul125/level3-project
    - name: revision
      value: main
