apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: user-pipeline
  namespace: tekton-pipelines
spec:
  workspaces:
  - name: shared-workspace

  params:
  - name: user-image
  - name: user-db-image

  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: https://github.com/abdul125/level3-project
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"

  - name: build-user-db
    taskRef:
      name: build-user-db
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: IMAGE
      value: $(params.user-db-image)
    - name: EXTRA_ARGS
      value: "--skip-tls-verify"

  - name: verify-digest-db
    runAfter:
    - build-user-db
    params:
    - name: digest
      value: $(tasks.build-user-db.results.IMAGE-DIGEST)
    taskSpec:
      params:
      - name: digest
      steps:
      - name: bash
        image: ubuntu
        script: |
          echo $(params.digest)
          case .$(params.digest) in
            ".sha"*) exit 0 ;;
            *)       echo "Digest value is not correct" && exit 1 ;;
          esac

  - name: build-user
    taskRef:
      name: build-user
    runAfter:
    - verify-digest-db
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: IMAGE
      value: $(params.user-image)
    - name: EXTRA_ARGS
      value: "--skip-tls-verify"


  - name: verify-digest
    runAfter:
    - build-user
    params:
    - name: digest
      value: $(tasks.kaniko.results.IMAGE-DIGEST)
    taskSpec:
      params:
      - name: digest
      steps:
      - name: bash
        image: ubuntu
        script: |
          echo $(params.digest)
          case .$(params.digest) in
            ".sha"*) exit 0 ;;
            *)       echo "Digest value is not correct" && exit 1 ;;
          esac

  - name: deploy-to-test
    taskRef:
      name: deploy-user
    runAfter:
    - verify-digest
    workspaces:
    - name: source
      workspace: shared-workspace
    params: 
    - name: namespace
      value: "test"

      # unit-test

  - name: deploy-to-production
      taskRef:
        name: deploy-user
      runAfter:
      - deploy-to-test
      workspaces:
      - name: source
        workspace: shared-workspace
      params: 
      - name: namespace
        value: "prod"

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-user-pipeline
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: run-user-pipeline
  params:
  - name: user-db-image
    value: abdul125/user-db:test
  - name: user-image
    value: abdul125/user:test

  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: kaniko-source-pvc

