apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa 
  namespace: tekton-pipelines
secrets:
- name: docker-auth
- name: git-auth

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-cluster-admin # solution 2
subjects:
  - kind: ServiceAccount
    name: tekton-sa
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
