apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-build-push-pr
  namespace: tekton-pipelines
spec:
  serviceAccountName: abdul
  pipelineRef:
    name: test-build-push
  resources:
  - name: repo
    resourceRef:
      name: level3-project
