apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-build-push
  namespace: tekton-pipelines
spec:
  resources:
    - name: repo
      type: git
  tasks:
    # Run application tests
    - name: build-frontend
      taskRef:
        name: frontend
      resources:
        inputs:
          - name: repo
            resource: repo

    # Build docker image and push to registry
    - name: build-shipping
      taskRef:
        name: shipping
      runAfter:
        - build-frontend
      resources:
        inputs:
          - name: repo
            resource: repo
