apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-carts
  namespace: tekton-pipelines
spec:
  params:
    - name: folderPath
      type: string
      default: /workspace/repo/deploy
    - name: namespace  
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: deploy
      image: bryandollery/terraform-packer-aws-alpine
      workingDir: $(params.folderPath)
      script: |
        #!/usr/bin/env bash
          echo "inside and trying params.path2context"
          ls -aAlth
          kubectl apply -f orders-db-dep.yml -f orders-db-svc.yml -n $(params.namespace) 
          kubectl apply -f orders-dep.yml -f orders-svc.yml -n $(params.namespace)
