apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
secrets:
- name: docker-auth

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deploy
rules:
- apiGroups: ["", "extensions", "apps", "networking.k8s.io"]
  resources: ["deployments", "deployments.apps", "replicasets", "pods", "services", "ingresses"]
  verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: deploy-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy
subjects:
  - kind: ServiceAccount
    name: tekton-sa
    namespace: test
