apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-carts
  namespace: tekton-pipelines
spec:
  params:
    - name: namespace

  workspaces:
  - name: source

  steps:
    - name: deploy
      workingDir: $(workspaces.source.path)/deploy
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "carts-db-dep.yml"
        - "-f"
        - "carts-db-svc.yml"
        - "-n"
        - "$(params.namespace)"
        - "apply"
        - "-f"
        - "carts-dep.yml"
        - "-f"
        - "carts-svc.yml"
        - "-n"
        - "$(params.namespace)"
