apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-test
  namespace: tekton-pipelines
spec:
  workspaces:
  - name: source
  steps:
    - name: file-explorer
      image: ubuntu
      script: |
       #!/usr/bin/env bash
       ls -aAgthl
       find 


    - name: e2e-test
      image: abdul125/e2e-test
      command: ["/bin/sh"]
      args:
        - "-c"
        - "/e2e/runner.sh"
