apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-test
  namespace: tekton-pipelines
spec:
  workspaces:
  - name: source
  params:
    - name: service-name
  steps:
    - name: wait-for-other-pods
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "wait"
        - "--for=condition=ready"
        - "pods"
        - "-l"
        - "name=$(params.service-name)"
        - "--timeout=900s"

    - name: e2e-test
      image: abdul125/e2e-test
      command: ["/bin/sh"]
      args:
        - "-c"
        - "/e2e/runner.sh"
