apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-test
  
spec:
  workspaces:
  - name: source
  steps:
    #- name: test-e2e-test
      #image: abdul125/e2e-test
      #command: ["/bin/sh"]
      #args:
        #- "find"
        #- "ls"
        #- "-aAthl"


    - name: e2e-test
      image: abdul125/e2e-test
      command: ["/bin/sh"]
      args:
        - "-c"
        - "/e2e/runner.sh"
