do:
	sed -i 's/microservice\/deploy/deploy/g' deploy-orders.yml && \
	sed -i 's/microservice\/deploy/deploy/g' deploy-payment.yml && \
	sed -i 's/microservice\/deploy/deploy/g' deploy-queue-master.yml &&\ 
	sed -i 's/microservice\/deploy/deploy/g' deploy-shipping.yml &&\
	sed -i 's/microservice\/deploy/deploy/g' deploy-user.yml 
