apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: shipping
  namespace: tekton-pipelines
spec:
  params:
    - name: shipping
      type: string
      default: /workspace/repo/microservices/shipping
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: list-files
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        ls -aAlth /workspace/repo
        ls -aAlth $(params.shipping)
        find $(params.shipping)
        echo $(params.shipping)
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.19.0
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
        - --dockerfile=$(params.shipping)/Dockerfile
        - --context=$(params.shipping)
        - --destination=abdul125/aa:shp-l3
