apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unit-test-frontend
  namespace: tekton-pipelines
spec:
  params:
    - name: folderPath
      type: string
      #default: $(workspaces.source.path)/microservice/front-end
  #workspaces:
    #name: source #it does not like workspaces
  steps:
    - name: unit-test 
      image: bryandollery/terraform-packer-aws-alpine
      script: |
        #!/usr/bin/env bash
        cd $(params.folderPath)
        ls -aAthl
        make build install itest
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock

  # As an implementation detail, this Task mounts the host's daemon socket.
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
