apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-payment
  namespace: tekton-pipelines
spec:
  params:
    - name: namespace

  resources:
    inputs:
      - name: repo
        type: git


  steps:
    - name: deploy
      workingDir: $(workspaces.source.path)/deploy
      image: bryandollery/terraform-packer-aws-alpine
      script: |
        #!/usr/bin/env bash
          echo "inside script"
          ls -aAlth
          kubectl apply -f payment-dep.yml -f payment-svc.yml -n $(params.namespace)
