apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: payment-pipeline
  namespace: tekton-pipelines
spec:
  resources:
    - name: repo
      type: git
  tasks:

    # build docker image
    - name: build-payment
      taskRef:
        name: build-payment
      resources:
        inputs:
          - name: repo
            resource: repo

    - name: deploy-to-test
      taskRef:
        name: deploy-payment
      runAfter:
      - build-payment
      resources:
        inputs:
          - name: repo
            resource: repo
      params: 
      - name: namespace
        value: "test"

    - name: deploy-to-prod
      taskRef:
        name: deploy-payment
      runAfter:
      - deploy-to-test
      resources:
        inputs:
          - name: repo
            resource: repo
      params: 
      - name: namespace
        value: "prod"


---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: payment-pr
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: payment-pipeline
  resources:
  - name: repo
    resourceRef:
      name: level3-project

