apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-shipping
  namespace: tekton-pipelines
spec:
  params:
    - name: folderPath
      type: string
      default: /workspace/repo/microservices/shipping
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.16.0
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - -v=debug
        - --dockerfile=$(params.folderPath)/Dockerfile
        - --destination=abdul125/shipping:1
        - --context=$(params.folderPath)
