apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: shipping-pipeline
  namespace: tekton-pipelines
spec:
  resources:
    - name: repo
      type: git
  tasks:

    # build docker image
    - name: build-shipping
      taskRef:
        name: build-shipping
      resources:
        inputs:
          - name: repo
            resource: repo

    # deploy to test namespace
    - name: deploy-shipping
      taskRef:
        name: deploy-shipping
      runAfter:
        - build-shipping
      resources:
        inputs:
          - name: repo
            resource: repo
      params:
      - name: namespace
        value: "test"

    # deploy to test namespace
    - name: deploy-shipping-prod
      taskRef:
        name: deploy-shipping
      runAfter:
        - deploy-shipping
      resources:
        inputs:
          - name: repo
            resource: repo
      params:
      - name: namespace
        value: "prod"


---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: shipping-pr
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: shipping-pipeline
  resources:
  - name: repo
    resourceRef:
      name: level3-project
