apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: carts-pr
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: carts-pipeline
  resources:
  - name: repo
    resourceRef:
      name: level3-project
