apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: queue-master-pipeline
  namespace: tekton-pipelines
spec:
  resources:
    - name: repo
      type: git
  tasks:

    # build docker image
    - name: build-queue-master
      taskRef:
        name: build-queue-master
      resources:
        inputs:
          - name: repo
            resource: repo

    # deploy to test namespace
    - name: deploy-queue-master
      taskRef:
        name: deploy-queue-master
      runAfter:
        - build-queue-master
      resources:
        inputs:
          - name: repo
            resource: repo
