apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-queue-master
  namespace: tekton-pipelines
spec:
  params:
    - name: folderPath
      type: string
      default: /workspace/repo/microservice/queue-master
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: deploy
      image: bryandollery/terraform-packer-aws-alpine
      script: |
        #!/usr/bin/env bash
          echo "inside and trying params.path2context"
          cd $(params.folderPath)
          ls -aAlth
          kubectl apply -f deploy.yml -f service.yml -n test
