apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-frontend
  namespace: tekton-pipelines
spec:
  params:
    - name: folderPath
      type: string
      default: /workspace/repo/deploy
    - name: namespace

  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: deploy
      image: bryandollery/terraform-packer-aws-alpine
      workingDir: $(params.folderPath)
      script: |
        #!/usr/bin/env bash
          echo "inside script"
          ls -aAlth
          #kubectl version --short=true
          kubectl apply -f front-end-dep.yml -f front-end-svc.yml -f ingress.yml -n $(params.namespace)
