apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-pipeline
  namespace: tekton-pipelines
spec:
  resources:
    - name: repo
      type: git
  tasks:
    # build docker image
    - name: build-frontend
      taskRef:
        name: build-frontend
      resources:
        inputs:
          - name: repo
            resource: repo

    # to-do unit-testing npm scanning 
    - name: deploy-to-test
      taskRef:
        name: deploy-frontend
      runAfter:
       - build-frontend
      resources:
        inputs:
          - name: repo
            resource: repo
      params: 
      - name: namespace
        value: "test"        

    # to-do deploy to prod namespace
    - name: deploy-to-production
      runAfter:
      - deploy-to-test
      taskRef:
        name: deploy-frontend
      resources:
        inputs:
          - name: repo
            resource: repo
      params: 
      - name: namespace
        value: "prod"  

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: frontend-pr
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: frontend-pipeline
  resources:
  - name: repo
    resourceRef:
      name: level3-project

