#!/bin/bash
FILE=/home/ubuntu/.docker/config.json
if [[ -f "$FILE" ]]; then
    echo "$FILE exists."

else 
    #echo "$FILE does not exist."
    docker login -u abdul125
    kubectl create secret generic docker-auth -n tekton-pipelines \
    --from-file=.dockerconfigjson=/home/ubuntu/.docker/config.json \
    --type=kubernetes.io/dockerconfigjson || true

fi

